#!/usr/bin/env node
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

'use strict';

const parser = require("./resources/sl-parser");

var text = process.argv.slice(2).join(' ');
text = text.replace(/\[.*?\]/g, '');
console.log('Parsing: ' +  text);
try {
    console.log(parser.parse(text));
} catch (ex) {
    var p = '';
    if (ex.location) {
        p = ex.location.start;
        p = ' line: ' + p.line + ' column: ' + p.column;
    }
    console.log(ex.message + p);
}
