#!/usr/bin/env node
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

'use strict';

const vaani = require('./parser');

var text = process.argv.slice(2).join(' ');
console.log('Parsing: ' +  text);
try {
    console.log(vaani.parse(text));
} catch (ex) {
    var p = '';
    if (ex.location) {
        p = ex.location.start;
        p = ' line: ' + p.line + ' column: ' + p.column;
    }
    console.log(ex.message + p);
}
