#!/usr/bin/env node
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

'use strict';
var lineReader = require('readline').createInterface({
  input: process.stdin
});
var fun = new Function('line', 'lineno', process.argv.slice(2, process.argv.length).join(' ') || 'return line;');
var lineno = 0;
lineReader.on('line', function(line) {
    var result = fun(line, lineno);
    lineno++;
    if (result) console.log(result);
});
